package:
  name: nginxparser
  version: 0.0.1

source:
  git_url: https://github.com/fatiherikli/nginxparser

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyparsing
